[theme]
# Główny różowy kolor akcentów (przyciski, suwaki)
primaryColor = "#ff0aef"

# Tło główne (ustawiamy na Twoje kremowe)
backgroundColor = "#FDF5E6"

# Tło bocznych paneli i formularzy (lekko ciemniejszy krem lub biały)
secondaryBackgroundColor = "#FDF5E6"

# Kolor tekstu (wymuszamy Twój grafitowy/czarny)
textColor = "#1A1A1A"

font = "sans serif"

[server]
runOnSave = true

[client]
toolbarMode = "minimal"
