[theme]
primaryColor = "#ff0aef"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#252525"
textColor = "#ffffff"
font = "sans serif"

[server]
runOnSave = true

[client]
toolbarMode = "minimal"
